// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/rules.proto

package rules

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN     Status = 0
	Status_OK          Status = 1
	Status_BLACKLISTED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "BLACKLISTED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":     0,
		"OK":          1,
		"BLACKLISTED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rules_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_rules_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_rules_proto_rawDescGZIP(), []int{0}
}

type CheckEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inn           string                 `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEntityRequest) Reset() {
	*x = CheckEntityRequest{}
	mi := &file_proto_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEntityRequest) ProtoMessage() {}

func (x *CheckEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEntityRequest.ProtoReflect.Descriptor instead.
func (*CheckEntityRequest) Descriptor() ([]byte, []int) {
	return file_proto_rules_proto_rawDescGZIP(), []int{0}
}

func (x *CheckEntityRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type CheckEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=rules.Status" json:"status,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEntityResponse) Reset() {
	*x = CheckEntityResponse{}
	mi := &file_proto_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEntityResponse) ProtoMessage() {}

func (x *CheckEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEntityResponse.ProtoReflect.Descriptor instead.
func (*CheckEntityResponse) Descriptor() ([]byte, []int) {
	return file_proto_rules_proto_rawDescGZIP(), []int{1}
}

func (x *CheckEntityResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *CheckEntityResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_proto_rules_proto protoreflect.FileDescriptor

const file_proto_rules_proto_rawDesc = "" +
	"\n" +
	"\x11proto/rules.proto\x12\x05rules\"&\n" +
	"\x12CheckEntityRequest\x12\x10\n" +
	"\x03inn\x18\x01 \x01(\tR\x03inn\"X\n" +
	"\x13CheckEntityResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.rules.StatusR\x06status\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory*.\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x0f\n" +
	"\vBLACKLISTED\x10\x022T\n" +
	"\fRulesService\x12D\n" +
	"\vCheckEntity\x12\x19.rules.CheckEntityRequest\x1a\x1a.rules.CheckEntityResponseB\x16Z\x14callmark/proto/rulesb\x06proto3"

var (
	file_proto_rules_proto_rawDescOnce sync.Once
	file_proto_rules_proto_rawDescData []byte
)

func file_proto_rules_proto_rawDescGZIP() []byte {
	file_proto_rules_proto_rawDescOnce.Do(func() {
		file_proto_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rules_proto_rawDesc), len(file_proto_rules_proto_rawDesc)))
	})
	return file_proto_rules_proto_rawDescData
}

var file_proto_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rules_proto_goTypes = []any{
	(Status)(0),                 // 0: rules.Status
	(*CheckEntityRequest)(nil),  // 1: rules.CheckEntityRequest
	(*CheckEntityResponse)(nil), // 2: rules.CheckEntityResponse
}
var file_proto_rules_proto_depIdxs = []int32{
	0, // 0: rules.CheckEntityResponse.status:type_name -> rules.Status
	1, // 1: rules.RulesService.CheckEntity:input_type -> rules.CheckEntityRequest
	2, // 2: rules.RulesService.CheckEntity:output_type -> rules.CheckEntityResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rules_proto_init() }
func file_proto_rules_proto_init() {
	if File_proto_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rules_proto_rawDesc), len(file_proto_rules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rules_proto_goTypes,
		DependencyIndexes: file_proto_rules_proto_depIdxs,
		EnumInfos:         file_proto_rules_proto_enumTypes,
		MessageInfos:      file_proto_rules_proto_msgTypes,
	}.Build()
	File_proto_rules_proto = out.File
	file_proto_rules_proto_goTypes = nil
	file_proto_rules_proto_depIdxs = nil
}
