// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/rules.proto

package rules

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RulesService_CheckEntity_FullMethodName = "/rules.RulesService/CheckEntity"
)

// RulesServiceClient is the client API for RulesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RulesServiceClient interface {
	CheckEntity(ctx context.Context, in *CheckEntityRequest, opts ...grpc.CallOption) (*CheckEntityResponse, error)
}

type rulesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRulesServiceClient(cc grpc.ClientConnInterface) RulesServiceClient {
	return &rulesServiceClient{cc}
}

func (c *rulesServiceClient) CheckEntity(ctx context.Context, in *CheckEntityRequest, opts ...grpc.CallOption) (*CheckEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEntityResponse)
	err := c.cc.Invoke(ctx, RulesService_CheckEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RulesServiceServer is the server API for RulesService service.
// All implementations must embed UnimplementedRulesServiceServer
// for forward compatibility.
type RulesServiceServer interface {
	CheckEntity(context.Context, *CheckEntityRequest) (*CheckEntityResponse, error)
	mustEmbedUnimplementedRulesServiceServer()
}

// UnimplementedRulesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRulesServiceServer struct{}

func (UnimplementedRulesServiceServer) CheckEntity(context.Context, *CheckEntityRequest) (*CheckEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckEntity not implemented")
}
func (UnimplementedRulesServiceServer) mustEmbedUnimplementedRulesServiceServer() {}
func (UnimplementedRulesServiceServer) testEmbeddedByValue()                      {}

// UnsafeRulesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RulesServiceServer will
// result in compilation errors.
type UnsafeRulesServiceServer interface {
	mustEmbedUnimplementedRulesServiceServer()
}

func RegisterRulesServiceServer(s grpc.ServiceRegistrar, srv RulesServiceServer) {
	// If the following call panics, it indicates UnimplementedRulesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RulesService_ServiceDesc, srv)
}

func _RulesService_CheckEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RulesServiceServer).CheckEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RulesService_CheckEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RulesServiceServer).CheckEntity(ctx, req.(*CheckEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RulesService_ServiceDesc is the grpc.ServiceDesc for RulesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RulesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rules.RulesService",
	HandlerType: (*RulesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckEntity",
			Handler:    _RulesService_CheckEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rules.proto",
}
